#!/bin/bash
# Copyright (c) [2019] SUSE LLC
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, contact SUSE LLC.
#
# To contact SUSE LLC about this file by physical or electronic mail, you may
# find current contact information at www.suse.com.


export Y2DIR=src

case x"$1" in
    xc )
        shift
        yast2 --ncurses hana_updater "$@"
        ;;
    xg )
        shift
        yast2 hana_updater "$@"
        ;;
    xdeb)
        echo "Running X"
        shift
        export Y2DEBUG=1
        yast2 hana_updater "$@"
        ;;
    xcd)
        shift
        export Y2DEBUG=1
        yast2 --ncurses hana_updater "$@"
        ;;
    'x-h')
        echo "Parameters:"
        echo "  c       Force ncurses"
        echo "  cd      Force ncurses with Debug Mode"
        echo "  g       Run in Qt"
        echo "  deb     Run in Qt with Debug Mode"
        echo 
        echo "Additional parameters:"
        echo "  skipto <stage_name>"
        echo "  setsys <SID>"
        exit 0
        ;;
    * )
        yast2 hana_updater "$@"
        ;;
esac
